### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by wargreen** [cannoneyed/fiddle#1]
Hi,
I try to test your OSC sequencer, but it fail to build.
Here the trace : 
```
$npm install
[...]
> concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

[1] 
[1] assert.js:89
[1]   throw new assert.AssertionError({
[1]   ^
[1] AssertionError: Current node version is not supported for development, expected "4.6.1" to satisfy ">=6.x".
[1]     at Object.<anonymous> (/home/leo/Téléchargements/fiddle/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
[1]     at Module._compile (module.js:409:26)
[1]     at Object.Module._extensions..js (module.js:416:10)
[1]     at Module.load (module.js:343:32)
[1]     at Function.Module._load (module.js:300:12)
[1]     at Function.Module.runMain (module.js:441:10)
[1]     at startup (node.js:139:18)
[1]     at node.js:974:3
[1] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 1
[0] Installing app dependencies for arch x64 to /home/leo/Téléchargements/fiddle/app
[0] install-app-deps exited with code 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mobx-logger@0.3.1 requires a peer of mobx@^2.4.2 but none was installed.
npm WARN mobx-connect@0.3.9 requires a peer of mobx@2.x but none was installed.
npm WARN mobx-connect@0.3.9 requires a peer of mobx-react@^3.5.x but none was installed.
npm WARN mobx-react-router@3.1.1 requires a peer of mobx@^2.5.2 but none was installed.
npm WARN @blueprintjs/core@1.5.0 requires a peer of react-addons-css-transition-group@^15.0.1 || ^0.14 but none was installed.
npm WARN mobx-inferno@0.1.3 requires a peer of mobx@2.x but none was installed.
npm ERR! Linux 4.6.0-1-rt-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 postinstall: `concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.10.0 postinstall script 'concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leo/Téléchargements/fiddle/npm-debug.log
```
[npm-debug.log.txt](https://github.com/cannoneyed/fiddle/files/702766/npm-debug.log.txt)

Thank you !

**Comment by cannoneyed** [comment]
@wargreen sorry to hear that! I'm actually **very** early in this project, and it's not anywhere near being ready for use.

Please follow the project, and I'll do my best to let everyone know once the first working version is available.

FYI - Your issue is because you're using node 4.6, and this project requires node 6. Check out [nvm](https://github.com/creationix/nvm) for managing node versions on your system. Good luck!

**Comment by wargreen** [comment]
Thank you a lot for your response.
Can you explain a little bit the features of fiddle, before I look for node6 ?
